### ISSUE TITLE
No syncs on Apr. 3 and 4, only 4 on Apr. 2

### ISSUE THREAD

**Issue by r-r-liu** [SwissCovid/swisscovid-app-ios#417]
It seems that my iPhone has not synced with the Backend on Apr. 3 and 4, and only four times on Apr. 2.  Is this expected behavior?  On Apr. 3 I was out and about and had the device with me.  On Apr. I also left home with it.

iPhone 12 Pro running iOS 14.4.2 SwissCovid 1.4.1 released 2021-03-25

**Comment by r-r-liu** [comment]
Shortly after posting the above I decided to restart the iPhone.  Since SwissCovid has been syncing with the backend as before?  Coincidence?

**Comment by UBaggeler** [comment]
Hi @r-r-liu. Sorry for the late reply. As far as we know, there was no change in the way Apple schedules our background tasks or backend issue. Feel free to send sysdiagnosis files when such issues appear, so we can look at them in detail. 

Best,
Fabian

**Comment by r-r-liu** [comment]
No such problem with subsequent updates of the app, so I'm closing this.
